### ISSUE TITLE
What is Listing~ ??

### ISSUE THREAD

**Issue by xsh6528** [rpicard/explore-flask#102]
In [configuration.rst](https://github.com/rpicard/explore-flask/blob/master/source/configuration.rst)

"In production, we would leave the variables in Listing~ out of instance/-config.py and it would fall back to the values defined in config.py."

It seems to be something else.

**Comment by rpicard** [comment]
Thanks for pointing that out: https://github.com/rpicard/explore-flask/commit/ea911154bd6508410b812f8be1dd803ae6f860c4
