### ISSUE TITLE
`import .views` in blueprinst.rst

### ISSUE THREAD

**Issue by n8henrie** [rpicard/explore-flask#92]
There are two places in [blueprints.rst](https://github.com/rpicard/explore-flask/blob/master/source/blueprints.rst) that include the line `import .views`, which produces a `SyntaxError` for me in both python 2.7.11 and python 3.5.1.

I believe this should be changed to `from . import views`.

**Comment by jeffwidman** [comment]
I think this should be closed now that #93 is merged

**Comment by rpicard** [comment]
@jeffwidman Good call. Thanks for taking a look.
