### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by wilfilho** [rpicard/explore-flask#94]
Hey man, the explore flask is a very good site for those who want to learn flask in the right way. Fuck would translate it to Portuguese (my native language). So I was wondering if there is a possibility and how I would organize the directory of this translation in the project, like, if I would add a call en folder in the same level of static, or something.

**Comment by rpicard** [comment]
It looks like Sphinx has a mechanism for translating: http://www.sphinx-doc.org/en/stable/intl.html

I've never used it myself, but if you want to work on using that I'd be happy to accept a pull request.

**Comment by wilfilho** [comment]
I understand, I will make a fork here to do pull requests. Thanks man!

**Comment by rpicard** [comment]
That sounds great. Thanks for taking the time!
