### ISSUE TITLE
Broken links in online version when url is not appended with /en/latest

### ISSUE THREAD

**Issue by Mazvel** [rpicard/explore-flask#97]
I came to the chapter https://exploreflask.com/organizing.html straight from Google. However when I was going to read other chapters I found that only the configuration chapter and the index chapter worked. Links to all other chapters resulted in 404 page. This is because when I enter the site with the standard url https://exploreflask.com it is routed to https://exploreflask.com/en/latest/, where all links work.

**Comment by rpicard** [comment]
Nice catch. I just moved the site over to Read the Docs. I guess Google will need to update its links. In the mean time I'll see about adding redirects.

**Comment by rpicard** [comment]
It should be working now. RTD has a prefix redirect feature that does this automatically if you set the prefix to `/`. Thanks for bringing it up. I doubt I would have noticed myself.

**Comment by Mazvel** [comment]
Glad to help and good job fixing this issue so quickly.
