### ISSUE TITLE
Configuration - Flask-SQLAlchemy link is dead

### ISSUE THREAD

**Issue by bcoia** [rpicard/explore-flask#98]
On the Configuration page, the link to Flask-SQLAlchemy's Configurations Keys page is dead. https://github.com/rpicard/explore-flask/blame/master/source/configuration.rst#L179

The updated link is: http://flask-sqlalchemy.pocoo.org/latest/config/#configuration-keys

**Comment by rpicard** [comment]
Nice catch, thanks!
